---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello
spec:
  selector:
    matchLabels:
      app: k8s-hello
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-hello
    spec:
      containers:
      - name: k8s-hello
        image: paulbouwer/hello-kubernetes:1.10
   

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: k8s-hello
